/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as FuentesRouteImport } from './routes/fuentes'
import { Route as MaquinariaRouteImport } from './routes/maquinaria'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as TrasladosRouteImport } from './routes/traslados'
import { Route as MaquinariaIndexRouteImport } from './routes/maquinaria.index'
import { Route as MaquinariaEquipmentIdRouteImport } from './routes/maquinaria.$equipmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const FuentesRoute = FuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinariaRoute = MaquinariaRouteImport.update({
  id: '/maquinaria',
  path: '/maquinaria',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrasladosRoute = TrasladosRouteImport.update({
  id: '/traslados',
  path: '/traslados',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinariaIndexRoute = MaquinariaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaquinariaRoute,
} as any)
const MaquinariaEquipmentIdRoute = MaquinariaEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => MaquinariaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/fuentes': typeof FuentesRoute
  '/maquinaria': typeof MaquinariaRouteWithChildren
  '/solicitudes': typeof SolicitudesRoute
  '/traslados': typeof TrasladosRoute
  '/maquinaria/$equipmentId': typeof MaquinariaEquipmentIdRoute
  '/maquinaria/': typeof MaquinariaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/fuentes': typeof FuentesRoute
  '/solicitudes': typeof SolicitudesRoute
  '/traslados': typeof TrasladosRoute
  '/maquinaria/$equipmentId': typeof MaquinariaEquipmentIdRoute
  '/maquinaria': typeof MaquinariaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/fuentes': typeof FuentesRoute
  '/maquinaria': typeof MaquinariaRouteWithChildren
  '/solicitudes': typeof SolicitudesRoute
  '/traslados': typeof TrasladosRoute
  '/maquinaria/$equipmentId': typeof MaquinariaEquipmentIdRoute
  '/maquinaria/': typeof MaquinariaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/fuentes'
    | '/maquinaria'
    | '/solicitudes'
    | '/traslados'
    | '/maquinaria/$equipmentId'
    | '/maquinaria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/fuentes'
    | '/solicitudes'
    | '/traslados'
    | '/maquinaria/$equipmentId'
    | '/maquinaria'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/fuentes'
    | '/maquinaria'
    | '/solicitudes'
    | '/traslados'
    | '/maquinaria/$equipmentId'
    | '/maquinaria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  FuentesRoute: typeof FuentesRoute
  MaquinariaRoute: typeof MaquinariaRouteWithChildren
  SolicitudesRoute: typeof SolicitudesRoute
  TrasladosRoute: typeof TrasladosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuentes': {
      id: '/fuentes'
      path: '/fuentes'
      fullPath: '/fuentes'
      preLoaderRoute: typeof FuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinaria': {
      id: '/maquinaria'
      path: '/maquinaria'
      fullPath: '/maquinaria'
      preLoaderRoute: typeof MaquinariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traslados': {
      id: '/traslados'
      path: '/traslados'
      fullPath: '/traslados'
      preLoaderRoute: typeof TrasladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinaria/': {
      id: '/maquinaria/'
      path: '/'
      fullPath: '/maquinaria/'
      preLoaderRoute: typeof MaquinariaIndexRouteImport
      parentRoute: typeof MaquinariaRoute
    }
    '/maquinaria/$equipmentId': {
      id: '/maquinaria/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/maquinaria/$equipmentId'
      preLoaderRoute: typeof MaquinariaEquipmentIdRouteImport
      parentRoute: typeof MaquinariaRoute
    }
  }
}

interface MaquinariaRouteChildren {
  MaquinariaEquipmentIdRoute: typeof MaquinariaEquipmentIdRoute
  MaquinariaIndexRoute: typeof MaquinariaIndexRoute
}

const MaquinariaRouteChildren: MaquinariaRouteChildren = {
  MaquinariaEquipmentIdRoute: MaquinariaEquipmentIdRoute,
  MaquinariaIndexRoute: MaquinariaIndexRoute,
}

const MaquinariaRouteWithChildren = MaquinariaRoute._addFileChildren(
  MaquinariaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  FuentesRoute: FuentesRoute,
  MaquinariaRoute: MaquinariaRouteWithChildren,
  SolicitudesRoute: SolicitudesRoute,
  TrasladosRoute: TrasladosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
